# Generated by Django 5.1.5 on 2025-04-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aigroup_attendanceguidesettings_billsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='postman',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.postman'),
            preserve_default=False,
        ),
    ]
