# Generated by Django 5.1.5 on 2025-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otp_remove_user_email_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('coin_amount', models.PositiveIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='plans/logos/'),
        ),
    ]
