# Generated by Django 5.1.5 on 2025-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chat_unique_open_chat_per_user_plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_open_chat_per_user_plan',
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('user', 'plan'), name='unique_chat_per_user_plan'),
        ),
    ]
