# Generated by Django 5.1.5 on 2025-05-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_chat_unique_open_chat_per_user_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='transaction_type',
        ),
    ]
