# Generated by Django 5.1.5 on 2025-05-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('lawyer', 'وکیل'), ('general', 'عمومی')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_replies', to='core.plan')),
            ],
        ),
    ]
